import { getGeminiClient, getGeminiModel } from './geminiService.js';
import mongoose from 'mongoose';

/**
 * Deterministic Fallback Workout Plan Generator
 * Produces structured, verified 7-day fitness plans tailored to role, fitness level,
 * primary goal, and daily physical activity context (vital for Community members).
 */
export function generateDeterministicPlan({
  role = 'student',
  fitnessLevel = 'beginner',
  goal = 'General Fitness',
  availableTimeMinutes = 30,
  dailyActivityContext = '',
}) {
  const normRole = (role || 'student').toLowerCase().trim();
  const normLevel = (fitnessLevel || 'beginner').toLowerCase().trim();
  const normGoal = (goal || 'General Fitness').trim();
  const time = Math.max(15, Math.min(60, Number(availableTimeMinutes) || 30));
  const diffLabel = normLevel === 'advanced' ? 'Advanced' : normLevel === 'intermediate' ? 'Intermediate' : 'Beginner';

  // COMMUNITY-SPECIFIC DETERMINISTIC PLANS (Context-Aware Physical Wellness)
  if (normRole === 'community' && dailyActivityContext) {
    const act = dailyActivityContext.toLowerCase();

    // 1. Farming / Agricultural Work: Focus on lumbar relief, hip mobility, core stability, recovery
    if (act.includes('farm') || act.includes('agri')) {
      return {
        source: 'deterministic_fallback',
        goal: normGoal,
        fitnessLevel: normLevel,
        availableTimeMinutes: time,
        dailyActivityContext,
        workouts: [
          {
            dayOfWeek: 'monday',
            focus: 'Spinal Decompression & Hip Opening',
            title: 'Lower Back & Pelvic Reset',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: "Child's Pose to Cobra Flow",
                category: 'Mobility',
                sets: 3,
                reps: 8,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Move gently between child pose and cobra, exhaling as you lengthen your lower back. Never force the spine.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'mat / clean floor',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Kneeling Hip Flexor Stretch',
                category: 'Flexibility',
                sets: 3,
                reps: 1,
                duration: '4 min (45s per side)',
                difficulty: 'Beginner',
                instructions: 'Tuck pelvis under and lean gently forward until hip flexor releases. Relieves field bending strain.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'none',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Bird-Dog Core Stability',
                category: 'Core',
                sets: 3,
                reps: 10,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Keep your hips level with the ground. Reach opposite arm and leg straight out with control.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'none',
              },
            ],
          },
          {
            dayOfWeek: 'tuesday',
            focus: 'Restorative Posture & Shoulder Recovery',
            title: 'Upper Spine & Scapular Balance',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Doorframe Chest & Bicep Opener',
                category: 'Mobility',
                sets: 3,
                reps: 1,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Place forearm against doorframe and gently rotate chest away. Counters forward hunching from tool use.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'doorframe or pillar',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Prone Y-T-W Scapular Raises',
                category: 'Strength',
                sets: 3,
                reps: 10,
                duration: '6 min',
                difficulty: 'Beginner',
                instructions: 'Lie face down and raise arms in Y, T, and W shapes squeezing the mid-back to strengthen postural muscles.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'mat',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Diaphragmatic Deep Breathing',
                category: 'Recovery',
                sets: 1,
                reps: 1,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Lie on your back with knees bent. Inhale slowly expanding the belly for 4 counts, exhale for 6 counts.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'none',
              },
            ],
          },
          {
            dayOfWeek: 'wednesday',
            focus: 'Gentle Cardio & Joint Lubrication',
            title: 'Easy Recovery Stroll & Joint Circles',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Light Recovery Walk',
                category: 'Endurance',
                sets: 1,
                reps: 1,
                duration: '15 min',
                difficulty: 'Beginner',
                instructions: 'Maintain a calm, comfortable pace with tall posture and relaxed swinging arms.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'comfortable footwear',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Standing Ankle & Knee Rotations',
                category: 'Mobility',
                sets: 2,
                reps: 10,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Rotate ankles smoothly 10 times clockwise and counter-clockwise to lubricate tired joints.',
                isCompleted: false,
                restSeconds: 15,
                equipment: 'none',
              },
            ],
          },
          {
            dayOfWeek: 'thursday',
            focus: 'Posterior Chain & Glute Activation',
            title: 'Balanced Lower Body Support',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Glute Bridge Holds',
                category: 'Strength',
                sets: 3,
                reps: 12,
                duration: '6 min',
                difficulty: 'Beginner',
                instructions: 'Drive through your heels to raise hips. Squeeze glutes at top for 2 seconds to support lower back.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'none',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Standing Side Leg Raises',
                category: 'Strength',
                sets: 3,
                reps: 12,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Keep torso upright and raise leg sideways to strengthen the hip abductors and stabilize pelvis.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'chair / wall for balance',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Seated Hamstring Stretch',
                category: 'Flexibility',
                sets: 2,
                reps: 1,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Sit tall, extend one leg and gently hinge forward at hips until gentle stretch is felt in hamstring.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'chair',
              },
            ],
          },
          {
            dayOfWeek: 'friday',
            focus: 'Core Stability & Thoracic Mobility',
            title: 'Midsection & Ribcage Expansion',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Thread the Needle Stretch',
                category: 'Mobility',
                sets: 3,
                reps: 8,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'On all fours, slide right arm under left ribcage, rotating thoracic spine gently. Repeat on both sides.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'mat',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Dead Bug Abdominal Stabilization',
                category: 'Core',
                sets: 3,
                reps: 10,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Lie on back, keep lumbar spine flush against floor while slowly lowering opposite arm and heel.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'none',
              },
            ],
          },
          {
            dayOfWeek: 'saturday',
            focus: 'Full Body Restorative Yoga',
            title: 'Agricultural Muscle Care',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Cat-Cow Spinal Articulation',
                category: 'Mobility',
                sets: 3,
                reps: 10,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Inhale while arching chest forward, exhale while rounding back and tucking chin.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'mat',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Supported Squat Hold',
                category: 'Mobility',
                sets: 3,
                reps: 1,
                duration: '3 min (45s hold)',
                difficulty: 'Beginner',
                instructions: 'Hold onto a doorframe or post and sit deep into a relaxed squat to open hips and ankles.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'sturdy post or frame',
              },
            ],
          },
          {
            dayOfWeek: 'sunday',
            focus: 'Rest & Complete Recovery',
            title: 'Rest & Hydration Ritual',
            durationMinutes: 15,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Legs-Up-The-Wall Elevation',
                category: 'Recovery',
                sets: 1,
                reps: 1,
                duration: '10 min',
                difficulty: 'Beginner',
                instructions: 'Lie with hips close to wall and legs straight up. Allows venous blood return and relieves tired legs.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'wall space',
              },
            ],
          },
        ],
      };
    }

    // 2. Mostly Sedentary: Focus on daily walking, posture correction, chest opening, gradual endurance
    if (act.includes('sedentary') || act.includes('desk') || act.includes('sitting')) {
      return {
        source: 'deterministic_fallback',
        goal: normGoal,
        fitnessLevel: normLevel,
        availableTimeMinutes: time,
        dailyActivityContext,
        workouts: [
          {
            dayOfWeek: 'monday',
            focus: 'Posture Reset & Foundation',
            title: 'Desk Decompression & Gentle Activation',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Wall Angels for Upper Back',
                category: 'Mobility',
                sets: 3,
                reps: 10,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Stand against wall with head, shoulders, and hips in contact. Slide arms up and down like a snow angel.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'wall space',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Chair Squats (Sit-to-Stand)',
                category: 'Strength',
                sets: 3,
                reps: 10,
                duration: '6 min',
                difficulty: 'Beginner',
                instructions: 'Stand in front of chair, hinge hips back and tap seat lightly before pressing up through heels.',
                isCompleted: false,
                restSeconds: 45,
                equipment: 'sturdy chair',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Brisk Walk',
                category: 'Endurance',
                sets: 1,
                reps: 1,
                duration: '15 min',
                difficulty: 'Beginner',
                instructions: 'Walk at an invigorating pace where you can still carry on a light conversation.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'walking shoes',
              },
            ],
          },
          {
            dayOfWeek: 'tuesday',
            focus: 'Core & Lower Body Mobility',
            title: 'Hip Flexor Release & Core Awakening',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Standing Hip Flexor Lunge Stretch',
                category: 'Flexibility',
                sets: 3,
                reps: 1,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Step one foot forward and tuck tailbone to release tight hip flexors from long sitting.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'none',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Incline Wall Push-ups',
                category: 'Strength',
                sets: 3,
                reps: 10,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Hands shoulder-width on wall. Lower chest smoothly and push away keeping core rigid.',
                isCompleted: false,
                restSeconds: 40,
                equipment: 'wall',
              },
            ],
          },
          {
            dayOfWeek: 'wednesday',
            focus: 'Aerobic Stamina Growth',
            title: 'Cardiovascular Brisk Walk & Breathing',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Outdoor / Treadmill Brisk Walk',
                category: 'Endurance',
                sets: 1,
                reps: 1,
                duration: '20 min',
                difficulty: 'Beginner',
                instructions: 'Focus on tall spine, gaze forward, relaxed shoulders, and active arm drive.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'walking shoes',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Standing Calf Stretches',
                category: 'Flexibility',
                sets: 2,
                reps: 1,
                duration: '3 min',
                difficulty: 'Beginner',
                instructions: 'Press back heel into floor with back leg straight to stretch gastrocnemius.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'wall',
              },
            ],
          },
          {
            dayOfWeek: 'thursday',
            focus: 'Glute Activation & Spinal Alignment',
            title: 'Posterior Strength & Spine Mobility',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Glute Bridges',
                category: 'Strength',
                sets: 3,
                reps: 12,
                duration: '6 min',
                difficulty: 'Beginner',
                instructions: 'Wake up inactive glute muscles by lifting hips and squeezing at the top.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'mat',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Cat-Cow Mobility Flow',
                category: 'Mobility',
                sets: 3,
                reps: 10,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Slowly transition between arching and rounding back to restore spinal fluidity.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'mat',
              },
            ],
          },
          {
            dayOfWeek: 'friday',
            focus: 'Full Body Functional Rhythm',
            title: 'Low-Impact Functional Conditioning',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Step-Jacks (Low Impact Jumping Jacks)',
                category: 'Endurance',
                sets: 3,
                reps: 20,
                duration: '6 min',
                difficulty: 'Beginner',
                instructions: 'Step one foot out to the side while raising arms overhead. Alternate feet without jumping.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'none',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Standing Cross-Body Knee Touches',
                category: 'Core',
                sets: 3,
                reps: 12,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Lift knee toward opposite elbow, engaging obliques and improving dynamic balance.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'none',
              },
            ],
          },
          {
            dayOfWeek: 'saturday',
            focus: 'Active Weekend Recreation',
            title: 'Outdoor Nature Walk & Mobility',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Continuous Leisure Walk',
                category: 'Endurance',
                sets: 1,
                reps: 1,
                duration: '25 min',
                difficulty: 'Beginner',
                instructions: 'Enjoy a sustained peaceful outdoor walk in a park, campus track, or neighbourhood.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'comfortable shoes',
              },
            ],
          },
          {
            dayOfWeek: 'sunday',
            focus: 'Rest & Full Body Mobility',
            title: 'Restorative Sunday Stretch',
            durationMinutes: 15,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Full Body Gentle Stretches',
                category: 'Flexibility',
                sets: 1,
                reps: 1,
                duration: '12 min',
                difficulty: 'Beginner',
                instructions: 'Perform slow neck rolls, shoulder rolls, hamstring stretches, and deep diaphragmatic breathing.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'none',
              },
            ],
          },
        ],
      };
    }

    // 3. Walking-intensive / Mostly Walking: Focus on foot/ankle care, calf stretches, core & upper body balance
    if (act.includes('walk')) {
      return {
        source: 'deterministic_fallback',
        goal: normGoal,
        fitnessLevel: normLevel,
        availableTimeMinutes: time,
        dailyActivityContext,
        workouts: [
          {
            dayOfWeek: 'monday',
            focus: 'Lower-Body Recovery & Foot Mobility',
            title: 'Plantar Care & Hip Relaxation',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Plantar Fascia Tennis Ball Roll',
                category: 'Recovery',
                sets: 2,
                reps: 1,
                duration: '4 min (2 min/foot)',
                difficulty: 'Beginner',
                instructions: 'Gently roll bottom of foot over ball to release tension in arches after extensive walking.',
                isCompleted: false,
                restSeconds: 15,
                equipment: 'tennis ball / rounded object',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Wall-Supported Calf & Achilles Stretch',
                category: 'Flexibility',
                sets: 3,
                reps: 1,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Keep back heel flat on floor and press forward to stretch gastrocnemius and soleus.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'wall',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Kneeling Quad & Hip Flexor Stretch',
                category: 'Flexibility',
                sets: 3,
                reps: 1,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Release front thigh tightness and restore hip extension balance.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'mat',
              },
            ],
          },
          {
            dayOfWeek: 'tuesday',
            focus: 'Upper Body Counter-Balance',
            title: 'Upper Torso & Postural Strength',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Incline Push-ups',
                category: 'Strength',
                sets: 3,
                reps: 10,
                duration: '6 min',
                difficulty: 'Beginner',
                instructions: 'Perform push-ups with hands on elevated bench or counter to build upper body strength without leg fatigue.',
                isCompleted: false,
                restSeconds: 40,
                equipment: 'table or sturdy bench',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Doorframe Towel Rows',
                category: 'Strength',
                sets: 3,
                reps: 10,
                duration: '6 min',
                difficulty: 'Beginner',
                instructions: 'Wrap towel around door handle, lean back, and pull chest forward squeezing mid-back.',
                isCompleted: false,
                restSeconds: 40,
                equipment: 'towel and sturdy door',
              },
            ],
          },
          {
            dayOfWeek: 'wednesday',
            focus: 'Core Stabilization & Pelvic Balance',
            title: 'Core Strengthening & Alignment',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Dead Bug Exercise',
                category: 'Core',
                sets: 3,
                reps: 10,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Maintain rigid core against floor while coordinating alternating limb movements.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'mat',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Side Plank from Knees',
                category: 'Core',
                sets: 3,
                reps: 1,
                duration: '4 min (20s hold/side)',
                difficulty: 'Beginner',
                instructions: 'Keep body in straight line from knees to shoulders to strengthen lateral stabilizers.',
                isCompleted: false,
                restSeconds: 30,
                equipment: 'mat',
              },
            ],
          },
          {
            dayOfWeek: 'thursday',
            focus: 'Active Restorative Stretching',
            title: 'Hip & Lower Spine Decompression',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Figure-4 Piriformis Stretch',
                category: 'Flexibility',
                sets: 3,
                reps: 1,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Lie on back, cross ankle over opposite knee, pull thigh toward chest to stretch deep glute muscles.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'mat',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Supine Spinal Twist',
                category: 'Mobility',
                sets: 2,
                reps: 1,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Gently allow knees to drop to one side while turning head to opposite side, opening chest and lower back.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'mat',
              },
            ],
          },
          {
            dayOfWeek: 'friday',
            focus: 'Balanced Upper Body Resistance',
            title: 'Chest & Shoulder Endurance',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Floor Plank Hold',
                category: 'Core',
                sets: 3,
                reps: 1,
                duration: '4 min (30s hold)',
                difficulty: 'Beginner',
                instructions: 'Hold forearm plank with straight spine, engaging core and glutes simultaneously.',
                isCompleted: false,
                restSeconds: 45,
                equipment: 'mat',
              },
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Arm Circles & Overhead Reach',
                category: 'Mobility',
                sets: 3,
                reps: 15,
                duration: '4 min',
                difficulty: 'Beginner',
                instructions: 'Controlled circles forwards and backwards to stimulate shoulder circulation.',
                isCompleted: false,
                restSeconds: 20,
                equipment: 'none',
              },
            ],
          },
          {
            dayOfWeek: 'saturday',
            focus: 'Low Impact Joint Movement',
            title: 'Easy Mobility & Joint Flow',
            durationMinutes: time,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Standing Hip Circles & Ankle Pumps',
                category: 'Mobility',
                sets: 3,
                reps: 10,
                duration: '5 min',
                difficulty: 'Beginner',
                instructions: 'Smooth, continuous rotational movements for lower body joints.',
                isCompleted: false,
                restSeconds: 15,
                equipment: 'none',
              },
            ],
          },
          {
            dayOfWeek: 'sunday',
            focus: 'Rest & Leg Elevation',
            title: 'Venous Drainage & Deep Rest',
            durationMinutes: 15,
            exercises: [
              {
                id: new mongoose.Types.ObjectId().toString(),
                name: 'Legs-Up-The-Wall Pose (Viparita Karani)',
                category: 'Recovery',
                sets: 1,
                reps: 1,
                duration: '12 min',
                difficulty: 'Beginner',
                instructions: 'Elevate legs against wall to relieve lymphatic and venous pressure after high daily mileage.',
                isCompleted: false,
                restSeconds: 0,
                equipment: 'wall',
              },
            ],
          },
        ],
      };
    }

    // 4. Manual / Physical Work / Household / Other Physical Contexts
    return {
      source: 'deterministic_fallback',
      goal: normGoal,
      fitnessLevel: normLevel,
      availableTimeMinutes: time,
      dailyActivityContext,
      workouts: [
        {
          dayOfWeek: 'monday',
          focus: 'Anti-Fatigue Joint Mobility',
          title: 'Joint Relief & Spine Balancing',
          durationMinutes: time,
          exercises: [
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Cat-Cow Mobility Stretches',
              category: 'Mobility',
              sets: 3,
              reps: 10,
              duration: '4 min',
              difficulty: 'Beginner',
              instructions: 'Relieve spinal compression from repetitive manual handling by flexing and extending gently.',
              isCompleted: false,
              restSeconds: 20,
              equipment: 'mat',
            },
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Standing Pec & Bicep Stretch',
              category: 'Flexibility',
              sets: 3,
              reps: 1,
              duration: '4 min',
              difficulty: 'Beginner',
              instructions: 'Stretch forearms, wrists, and chest muscles tired from gripping and carrying.',
              isCompleted: false,
              restSeconds: 20,
              equipment: 'wall',
            },
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Bird-Dog Core Holds',
              category: 'Core',
              sets: 3,
              reps: 10,
              duration: '5 min',
              difficulty: 'Beginner',
              instructions: 'Promote rotational core strength to safeguard lower back during lifting tasks.',
              isCompleted: false,
              restSeconds: 30,
              equipment: 'mat',
            },
          ],
        },
        {
          dayOfWeek: 'tuesday',
          focus: 'Lower Back & Glute Balancing',
          title: 'Pelvic Stabilization & Hip Release',
          durationMinutes: time,
          exercises: [
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Glute Bridges',
              category: 'Strength',
              sets: 3,
              reps: 10,
              duration: '5 min',
              difficulty: 'Beginner',
              instructions: 'Strengthen glutes to take shear strain off the lumbar spine.',
              isCompleted: false,
              restSeconds: 30,
              equipment: 'none',
            },
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Kneeling Hip Flexor Stretch',
              category: 'Flexibility',
              sets: 3,
              reps: 1,
              duration: '4 min',
              difficulty: 'Beginner',
              instructions: 'Open front hips to counteract chronic lumbar lordosis.',
              isCompleted: false,
              restSeconds: 20,
              equipment: 'none',
            },
          ],
        },
        {
          dayOfWeek: 'wednesday',
          focus: 'Active Recovery Walk',
          title: 'Easy Cardiovascular Restoration',
          durationMinutes: time,
          exercises: [
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Easy Paced Walk',
              category: 'Endurance',
              sets: 1,
              reps: 1,
              duration: '20 min',
              difficulty: 'Beginner',
              instructions: 'Walk with relaxed arms and easy breathing to clear muscular metabolites.',
              isCompleted: false,
              restSeconds: 0,
              equipment: 'shoes',
            },
          ],
        },
        {
          dayOfWeek: 'thursday',
          focus: 'Upper Back & Shoulder Posture',
          title: 'Scapular Stability & Breathing',
          durationMinutes: time,
          exercises: [
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Wall Slides for Posture',
              category: 'Mobility',
              sets: 3,
              reps: 10,
              duration: '5 min',
              difficulty: 'Beginner',
              instructions: 'Slide forearms along wall, keeping chin tucked and shoulder blades depressed.',
              isCompleted: false,
              restSeconds: 30,
              equipment: 'wall',
            },
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Dead Bug Stabilization',
              category: 'Core',
              sets: 3,
              reps: 10,
              duration: '5 min',
              difficulty: 'Beginner',
              instructions: 'Engage transverse abdominis without holding your breath.',
              isCompleted: false,
              restSeconds: 30,
              equipment: 'none',
            },
          ],
        },
        {
          dayOfWeek: 'friday',
          focus: 'Total Body Mobility Flow',
          title: 'Full Body Joint Decompression',
          durationMinutes: time,
          exercises: [
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: "Child's Pose Breathing",
              category: 'Recovery',
              sets: 3,
              reps: 1,
              duration: '5 min',
              difficulty: 'Beginner',
              instructions: 'Lengthen spine and breath into the back ribcage for deep nervous system relaxation.',
              isCompleted: false,
              restSeconds: 20,
              equipment: 'mat',
            },
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Gentle Hamstring & Calf Stretch',
              category: 'Flexibility',
              sets: 2,
              reps: 1,
              duration: '4 min',
              difficulty: 'Beginner',
              instructions: 'Relax into hamstring stretch without bouncing or straining.',
              isCompleted: false,
              restSeconds: 20,
              equipment: 'none',
            },
          ],
        },
        {
          dayOfWeek: 'saturday',
          focus: 'Light Leisure Movement',
          title: 'Gentle Movement Circulation',
          durationMinutes: time,
          exercises: [
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Outdoor Stroll & Wrist Circles',
              category: 'Mobility',
              sets: 1,
              reps: 1,
              duration: '20 min',
              difficulty: 'Beginner',
              instructions: 'Leisurely pace with frequent wrist and shoulder rolls.',
              isCompleted: false,
              restSeconds: 0,
              equipment: 'none',
            },
          ],
        },
        {
          dayOfWeek: 'sunday',
          focus: 'Rest & Recovery',
          title: 'Rest & Deep Rejuvenation',
          durationMinutes: 15,
          exercises: [
            {
              id: new mongoose.Types.ObjectId().toString(),
              name: 'Leg Elevation & Rest',
              category: 'Recovery',
              sets: 1,
              reps: 1,
              duration: '12 min',
              difficulty: 'Beginner',
              instructions: 'Elevate feet on cushions or wall to support recovery.',
              isCompleted: false,
              restSeconds: 0,
              equipment: 'cushion / bed',
            },
          ],
        },
      ],
    };
  }

  // STUDENT PERSONALIZED DETERMINISTIC PLANS (Goal & Assessment Calibrated)
  return {
    source: 'deterministic_fallback',
    goal: normGoal,
    fitnessLevel: normLevel,
    availableTimeMinutes: time,
    dailyActivityContext: '',
    workouts: [
      {
        dayOfWeek: 'monday',
        focus: 'Strength & Core Foundation',
        title: 'Upper Body & Core Power',
        durationMinutes: time,
        exercises: [
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: normLevel === 'advanced' ? 'Decline Push-ups' : normLevel === 'intermediate' ? 'Standard Push-ups' : 'Knee or Wall Push-ups',
            category: 'Strength',
            sets: 3,
            reps: normLevel === 'advanced' ? 15 : normLevel === 'intermediate' ? 12 : 8,
            duration: '',
            difficulty: diffLabel,
            instructions: 'Keep body in a straight plank, lower chest to floor level and press up forcefully.',
            isCompleted: false,
            restSeconds: 45,
            equipment: 'none / bodyweight',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: normLevel === 'advanced' ? 'Jump Squats' : 'Bodyweight Air Squats',
            category: 'Strength',
            sets: 3,
            reps: normLevel === 'advanced' ? 15 : 12,
            duration: '',
            difficulty: diffLabel,
            instructions: 'Hinge hips back and drive through mid-foot to stand up tall with glute contraction.',
            isCompleted: false,
            restSeconds: 45,
            equipment: 'none',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Forearm Plank Hold',
            category: 'Core',
            sets: 3,
            reps: 1,
            duration: normLevel === 'advanced' ? '45s hold' : normLevel === 'intermediate' ? '30s hold' : '20s hold',
            durationSeconds: normLevel === 'advanced' ? 45 : normLevel === 'intermediate' ? 30 : 20,
            difficulty: diffLabel,
            instructions: 'Maintain rigid core, pull belly button inward, do not let hips sag.',
            isCompleted: false,
            restSeconds: 30,
            equipment: 'mat',
          },
        ],
      },
      {
        dayOfWeek: 'tuesday',
        focus: 'Cardiovascular Endurance & Agility',
        title: 'Aerobic Intervals & Footwork',
        durationMinutes: time,
        exercises: [
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Brisk Interval Run / Shuttle Drills',
            category: 'Endurance',
            sets: 1,
            reps: 1,
            duration: `${Math.round(time * 0.6)} min`,
            difficulty: diffLabel,
            instructions: 'Alternate 2 minutes of brisk running with 1 minute of recovery walking.',
            isCompleted: false,
            restSeconds: 0,
            equipment: 'track / open field',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Mountain Climbers',
            category: 'Endurance',
            sets: 3,
            reps: normLevel === 'advanced' ? 30 : 20,
            duration: '4 min',
            difficulty: diffLabel,
            instructions: 'Drive knees toward chest in rhythmic cadence keeping shoulders over wrists.',
            isCompleted: false,
            restSeconds: 30,
            equipment: 'none',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Standing Quad & Hamstring Cool-down',
            category: 'Flexibility',
            sets: 2,
            reps: 1,
            duration: '4 min',
            difficulty: 'Beginner',
            instructions: 'Hold each stretch for 30 seconds with deep rhythmic breathing.',
            isCompleted: false,
            restSeconds: 15,
            equipment: 'none',
          },
        ],
      },
      {
        dayOfWeek: 'wednesday',
        focus: 'Active Mobility & Kinetic Balance',
        title: 'Hip Mobility & Spine Alignment',
        durationMinutes: time,
        exercises: [
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Deep Squat to Thoracic Rotation',
            category: 'Mobility',
            sets: 3,
            reps: 8,
            duration: '5 min',
            difficulty: 'Beginner',
            instructions: 'Hold deep squat and rotate arm skyward, following hand with your eyes.',
            isCompleted: false,
            restSeconds: 30,
            equipment: 'none',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Bird-Dog & Dead Bug Supersets',
            category: 'Core',
            sets: 3,
            reps: 10,
            duration: '6 min',
            difficulty: diffLabel,
            instructions: 'Move with control to develop cross-body stability and pelvic equilibrium.',
            isCompleted: false,
            restSeconds: 30,
            equipment: 'mat',
          },
        ],
      },
      {
        dayOfWeek: 'thursday',
        focus: 'Lower Body Power & Posture',
        title: 'Squats, Lunges & Hip Drive',
        durationMinutes: time,
        exercises: [
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Alternating Forward / Reverse Lunges',
            category: 'Strength',
            sets: 3,
            reps: normLevel === 'advanced' ? 16 : 10,
            duration: '6 min',
            difficulty: diffLabel,
            instructions: 'Take a generous step, lower back knee gently, keeping front knee behind toe line.',
            isCompleted: false,
            restSeconds: 45,
            equipment: 'none',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Glute Bridge Holds',
            category: 'Strength',
            sets: 3,
            reps: 12,
            duration: '5 min',
            difficulty: diffLabel,
            instructions: 'Drive through heels, squeeze glutes at peak height for 2 seconds.',
            isCompleted: false,
            restSeconds: 30,
            equipment: 'none',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Standing Calf Raises',
            category: 'Strength',
            sets: 3,
            reps: 15,
            duration: '4 min',
            difficulty: 'Beginner',
            instructions: 'Rise fully onto balls of feet, hold 1s at apex, lower slowly.',
            isCompleted: false,
            restSeconds: 25,
            equipment: 'wall for balance',
          },
        ],
      },
      {
        dayOfWeek: 'friday',
        focus: 'Upper Body & Stamina Conditioning',
        title: 'Push-up Endurance & Core Burn',
        durationMinutes: time,
        exercises: [
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Push-up Sets to Fatigue Buffer',
            category: 'Strength',
            sets: 3,
            reps: normLevel === 'advanced' ? 15 : normLevel === 'intermediate' ? 10 : 6,
            duration: '5 min',
            difficulty: diffLabel,
            instructions: 'Complete sets maintaining rigid midline and clean elbow tracking.',
            isCompleted: false,
            restSeconds: 60,
            equipment: 'none',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Bicycle Crunches',
            category: 'Core',
            sets: 3,
            reps: normLevel === 'advanced' ? 24 : 16,
            duration: '5 min',
            difficulty: diffLabel,
            instructions: 'Slow and deliberate rotational tempo. Shoulder blade clears the floor.',
            isCompleted: false,
            restSeconds: 30,
            equipment: 'mat',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Jumping Jacks / Shadow Boxing',
            category: 'Endurance',
            sets: 3,
            reps: 30,
            duration: '5 min',
            difficulty: diffLabel,
            instructions: 'Stay light on the balls of your feet and maintain quick rhythmic breathing.',
            isCompleted: false,
            restSeconds: 30,
            equipment: 'none',
          },
        ],
      },
      {
        dayOfWeek: 'saturday',
        focus: 'Athletic Play & Sport Agility',
        title: 'Sprint Acceleration or Active Sport',
        durationMinutes: time,
        exercises: [
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Sport Play / Sprint Drills',
            category: 'Endurance',
            sets: 1,
            reps: 1,
            duration: `${Math.round(time * 0.7)} min`,
            difficulty: diffLabel,
            instructions: 'Play football, cricket, badminton, basketball, or perform short 30m sprint accelerations.',
            isCompleted: false,
            restSeconds: 0,
            equipment: 'sports gear / field',
          },
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Hamstring & Groin Stretches',
            category: 'Flexibility',
            sets: 2,
            reps: 1,
            duration: '5 min',
            difficulty: 'Beginner',
            instructions: 'Gentle post-activity flexibility holds to enhance recovery.',
            isCompleted: false,
            restSeconds: 15,
            equipment: 'none',
          },
        ],
      },
      {
        dayOfWeek: 'sunday',
        focus: 'Rest, Hydration & Regeneration',
        title: 'Complete Rest & Growth',
        durationMinutes: 15,
        exercises: [
          {
            id: new mongoose.Types.ObjectId().toString(),
            name: 'Full Body Static Stretch & Hydration',
            category: 'Recovery',
            sets: 1,
            reps: 1,
            duration: '10 min',
            difficulty: 'Beginner',
            instructions: 'Hydrate adequately, sleep 8+ hours, and let muscle fibers repair for the upcoming week.',
            isCompleted: false,
            restSeconds: 0,
            equipment: 'water bottle',
          },
        ],
      },
    ],
  };
}

/**
 * AI Workout Plan Generator with Seamless Deterministic Fallback
 */
export async function generateWorkoutPlan({
  role = 'student',
  fitnessLevel = 'beginner',
  goal = 'General Fitness',
  availableTimeMinutes = 30,
  dailyActivityContext = '',
  studentAssessment = null,
}) {
  const normRole = (role || 'student').toLowerCase().trim();
  const normLevel = (fitnessLevel || 'beginner').toLowerCase().trim();
  const normGoal = (goal || 'General Fitness').trim();
  const time = Math.max(15, Math.min(60, Number(availableTimeMinutes) || 30));

  // Try Gemini AI if available
  try {
    const ai = getGeminiClient();
    const model = getGeminiModel();

    let contextDetails = `Role: ${normRole}\nGoal: ${normGoal}\nFitness Level: ${normLevel}\nAvailable Time: ${time} minutes per day`;
    if (normRole === 'community' && dailyActivityContext) {
      contextDetails += `\nDaily Physical Activity / Work Context: ${dailyActivityContext}\nIMPORTANT FOR COMMUNITY WORKERS: Do NOT add heavy spinal fatigue on top of physical labor (farming, manual work, walking). Prioritize mobility, spinal decompression, posture, recovery, and balanced joint support.`;
    }
    if (studentAssessment) {
      contextDetails += `\nStudent Physical Baseline: Push-ups: ${studentAssessment.pushUps || 0} reps, Sit-ups: ${studentAssessment.sitUps || 0} reps, 50m Sprint: ${studentAssessment.runTime || 0}s, Flexibility: ${studentAssessment.flexibility || 0}cm, Shuttle: ${studentAssessment.shuttleRun || 0}s, Score: ${studentAssessment.overallScore || 'N/A'}`;
    }

    const promptText = `
You are an expert sports physiologist and functional athletic coach for Athletica.
Create a structured 7-day Weekly Workout Plan (Monday through Sunday) personalized to this user profile:

${contextDetails}

CRITICAL INSTRUCTIONS:
1. Return exactly 7 workout days (monday, tuesday, wednesday, thursday, friday, saturday, sunday).
2. Each day must include:
   - "dayOfWeek": string ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')
   - "focus": short string (e.g. "Strength + Mobility", "Endurance & Recovery")
   - "title": short title (e.g. "Upper Body & Posture")
   - "durationMinutes": integer around ${time}
   - "exercises": list of 2 to 4 exercises
3. Each exercise must include:
   - "name": exercise name
   - "category": 'Strength' | 'Mobility' | 'Endurance' | 'Core' | 'Recovery' | 'Flexibility'
   - "sets": integer (e.g. 3)
   - "reps": integer (e.g. 10)
   - "duration": string (e.g. "20 min" or "5 min" or "")
   - "difficulty": 'Beginner' | 'Intermediate' | 'Advanced'
   - "instructions": 1-2 sentence coaching cue focusing on proper posture and safe form
   - "isCompleted": false
   - "restSeconds": integer (e.g. 30)
   - "equipment": string (e.g. "none / bodyweight")
4. No medical diagnosis or dangerous loading.
`;

    const workoutPlanResponseSchema = {
      type: 'OBJECT',
      properties: {
        workouts: {
          type: 'ARRAY',
          items: {
            type: 'OBJECT',
            properties: {
              dayOfWeek: { type: 'STRING' },
              focus: { type: 'STRING' },
              title: { type: 'STRING' },
              durationMinutes: { type: 'INTEGER' },
              exercises: {
                type: 'ARRAY',
                items: {
                  type: 'OBJECT',
                  properties: {
                    name: { type: 'STRING' },
                    category: { type: 'STRING' },
                    sets: { type: 'INTEGER' },
                    reps: { type: 'INTEGER' },
                    duration: { type: 'STRING' },
                    difficulty: { type: 'STRING' },
                    instructions: { type: 'STRING' },
                    isCompleted: { type: 'BOOLEAN' },
                    restSeconds: { type: 'INTEGER' },
                    equipment: { type: 'STRING' },
                  },
                  required: ['name', 'category', 'sets', 'reps', 'difficulty', 'instructions'],
                },
              },
            },
            required: ['dayOfWeek', 'focus', 'title', 'durationMinutes', 'exercises'],
          },
        },
      },
      required: ['workouts'],
    };

    const response = await ai.models.generateContent({
      model,
      contents: [promptText],
      config: {
        responseMimeType: 'application/json',
        responseSchema: workoutPlanResponseSchema,
        temperature: 0.2,
      },
    });

    if (response?.text) {
      const parsed = JSON.parse(response.text);
      if (Array.isArray(parsed?.workouts) && parsed.workouts.length >= 5) {
        // Normalize IDs and completed states
        const normalizedWorkouts = parsed.workouts.map((w) => ({
          dayOfWeek: String(w.dayOfWeek || 'monday').toLowerCase().trim(),
          focus: String(w.focus || 'Fitness & Mobility').trim(),
          title: String(w.title || 'Daily Workout').trim(),
          durationMinutes: Number(w.durationMinutes) || time,
          exercises: (w.exercises || []).map((ex) => ({
            id: new mongoose.Types.ObjectId().toString(),
            name: String(ex.name || 'Exercise').trim(),
            category: String(ex.category || 'General').trim(),
            sets: Number(ex.sets) || 3,
            reps: Number(ex.reps) || 10,
            duration: String(ex.duration || '').trim(),
            durationSeconds: 0,
            difficulty: String(ex.difficulty || 'Beginner').trim(),
            instructions: String(ex.instructions || '').trim(),
            isCompleted: false,
            completedAt: null,
            restSeconds: Number(ex.restSeconds) || 30,
            equipment: String(ex.equipment || 'none / bodyweight').trim(),
            notes: '',
          })),
        }));

        return {
          source: 'ai_generated',
          goal: normGoal,
          fitnessLevel: normLevel,
          availableTimeMinutes: time,
          dailyActivityContext,
          workouts: normalizedWorkouts,
        };
      }
    }
  } catch (err) {
    console.warn(`Gemini AI workout generation skipped or failed (${err?.message || 'Quota/Network'}). Utilizing certified deterministic fallback.`);
  }

  // Seamless Deterministic Fallback Engine
  return generateDeterministicPlan({
    role: normRole,
    fitnessLevel: normLevel,
    goal: normGoal,
    availableTimeMinutes: time,
    dailyActivityContext,
  });
}
